
"Leader
let mapleader = " "
let maplocalleader = "\\"
:source ~/.dotfiles/gundo_config.vim
:source ~/.dotfiles/ycm_config.vim
:source ~/.dotfiles/plugins.vim
:source ~/.dotfiles/options.vim
:source ~/.dotfiles/natrew_config.vim
:source ~/.dotfiles/delimitmate.vim
:source ~/.dotfiles/bindings.vim
:source ~/.dotfiles/color_syntax.vim
:source ~/.dotfiles/autocommands.vim
":source ~/.dotfiles/auto_start.vim
source ~/.dotfiles/goyo_config.vim

"Set on the left a diff tab
":diffthis
let g:hardtime_default_on = 1
set statusline+=%{gutentags#statusline()}
"packadd! matchit
" Start interactive EasyAlign in visual mode (e.g. vipga)
xmap gaa <Plug>(EasyAlign)

" Start interactive EasyAlign for a motion/text object (e.g. gaip)
nmap gaa <Plug>(EasyAlign)
